"""Single source of truth for backend AI model identifiers."""


def _provider_model(provider: str, model: str) -> str:
    return f"{provider}:{model}"


# Mistral
MISTRAL_BEST_MODEL = "mistral-large-latest"
MISTRAL_MEDIUM_MODEL = "mistral-medium-latest"
MISTRAL_FAST_MODEL = "mistral-small-latest"
MISTRAL_VISION_MODEL = "pixtral-large-latest"
MISTRAL_OCR_MODEL = "mistral-ocr-latest"
MISTRAL_TTS_MODEL = "voxtral-mini-tts-latest"
MISTRAL_TRANSCRIPTION_MODEL = "voxtral-mini-latest"
MISTRAL_REASONING_MODEL = "magistral-medium-2509"

MISTRAL_BEST_AGENT = _provider_model("mistral", MISTRAL_BEST_MODEL)
MISTRAL_MEDIUM_AGENT = _provider_model("mistral", MISTRAL_MEDIUM_MODEL)
MISTRAL_FAST_AGENT = _provider_model("mistral", MISTRAL_FAST_MODEL)
MISTRAL_VISION_AGENT = _provider_model("mistral", MISTRAL_VISION_MODEL)
MISTRAL_REASONING_AGENT = _provider_model("magistral", MISTRAL_REASONING_MODEL)

# OpenAI
OPENAI_BEST_MODEL = "gpt-5.6-luna"
OPENAI_MEDIUM_MODEL = "gpt-5.2"
OPENAI_STANDARD_MODEL = "gpt-4o"
OPENAI_FAST_MODEL = "gpt-4o-mini"
OPENAI_REASONING_MODEL = "o1"
OPENAI_IMAGE_MODEL = "gpt-image-1"
OPENAI_LEGACY_IMAGE_MODEL = "dall-e-3"
OPENAI_TTS_MODEL = "tts-1"
OPENAI_TRANSCRIPTION_MODEL = "whisper-1"

OPENAI_BEST_AGENT = _provider_model("openai", OPENAI_BEST_MODEL)
OPENAI_MEDIUM_AGENT = _provider_model("openai", OPENAI_MEDIUM_MODEL)
OPENAI_STANDARD_AGENT = _provider_model("openai", OPENAI_STANDARD_MODEL)
OPENAI_FAST_AGENT = _provider_model("openai", OPENAI_FAST_MODEL)
OPENAI_REASONING_AGENT = _provider_model("openai", OPENAI_REASONING_MODEL)

# Anthropic

ANTHROPIC_OPUS_5_MODEL = "claude-opus-5"
ANTHROPIC_SONNET_5_MODEL = "claude-sonnet-5"
ANTHROPIC_COMPATIBILITY_ALIAS = "claude-3-5-sonnet"
ANTHROPIC_COMPATIBILITY_MODEL = "claude-3-5-sonnet-20241022"
ANTHROPIC_BEST_MODEL = ANTHROPIC_OPUS_5_MODEL
ANTHROPIC_MEDIUM_MODEL = ANTHROPIC_SONNET_5_MODEL
ANTHROPIC_FALLBACK_MODEL = "claude-sonnet-4-5"
ANTHROPIC_FAST_MODEL = "claude-haiku-4-5"

ANTHROPIC_BEST_AGENT = _provider_model("anthropic", ANTHROPIC_BEST_MODEL)
ANTHROPIC_MEDIUM_AGENT = _provider_model("anthropic", ANTHROPIC_MEDIUM_MODEL)
ANTHROPIC_FALLBACK_AGENT = _provider_model("anthropic", ANTHROPIC_FALLBACK_MODEL)
ANTHROPIC_FAST_AGENT = _provider_model("anthropic", ANTHROPIC_FAST_MODEL)
ANTHROPIC_OPUS_5_AGENT = _provider_model("anthropic", ANTHROPIC_OPUS_5_MODEL)
ANTHROPIC_SONNET_5_AGENT = _provider_model("anthropic", ANTHROPIC_SONNET_5_MODEL)

# Fable
FABLE_BEST_MODEL = "fable-5.1"
FABLE_BEST_AGENT = _provider_model("fable", FABLE_BEST_MODEL)

# DeepSeek
DEEPSEEK_BEST_MODEL = "deepseek-v4-pro"
DEEPSEEK_FAST_MODEL = "deepseek-v4-flash"
DEEPSEEK_REASONING_MODEL = "deepseek-reasoner"
DEEPSEEK_CHAT_MODEL = "deepseek-chat"

DEEPSEEK_BEST_AGENT = _provider_model("deepseek", DEEPSEEK_BEST_MODEL)
DEEPSEEK_FAST_AGENT = _provider_model("deepseek", DEEPSEEK_FAST_MODEL)
DEEPSEEK_REASONING_AGENT = _provider_model("deepseek", DEEPSEEK_REASONING_MODEL)
DEEPSEEK_CHAT_AGENT = _provider_model("deepseek", DEEPSEEK_CHAT_MODEL)

# Google
GOOGLE_FAST_MODEL = "gemini-2-flash-lite"
GOOGLE_IMAGE_MODEL = "gemini-2.5-flash-image"
GOOGLE_BEST_IMAGE_MODEL = "gemini-3-pro-image-preview"
GOOGLE_IMAGE_GENERATION_MODEL = "imagen-4.0-generate-001"

GOOGLE_FAST_AGENT = _provider_model("google", GOOGLE_FAST_MODEL)

# Compatibility aliases
MISTRAL_LARGE = MISTRAL_BEST_MODEL
MISTRAL_MEDIUM = MISTRAL_MEDIUM_MODEL
MISTRAL_SMALL = MISTRAL_FAST_MODEL
PIXTRAL_LARGE = MISTRAL_VISION_MODEL
MISTRAL_OCR = MISTRAL_OCR_MODEL
VOXTRAL_TTS = MISTRAL_TTS_MODEL
VOXTRAL_TRANSCRIPTION = MISTRAL_TRANSCRIPTION_MODEL
MAGISTRAL_MEDIUM = MISTRAL_REASONING_MODEL
MISTRAL_LARGE_AGENT = MISTRAL_BEST_AGENT
MISTRAL_SMALL_AGENT = MISTRAL_FAST_AGENT
PIXTRAL_LARGE_AGENT = MISTRAL_VISION_AGENT
MAGISTRAL_MEDIUM_AGENT = MISTRAL_REASONING_AGENT

OPENAI_GPT_5_4 = OPENAI_BEST_MODEL
OPENAI_GPT_5_2 = OPENAI_MEDIUM_MODEL
OPENAI_GPT_4O = OPENAI_STANDARD_MODEL
OPENAI_GPT_4O_MINI = OPENAI_FAST_MODEL
OPENAI_O1 = OPENAI_REASONING_MODEL
OPENAI_IMAGE = OPENAI_IMAGE_MODEL
OPENAI_DALL_E_3 = OPENAI_LEGACY_IMAGE_MODEL
OPENAI_TTS = OPENAI_TTS_MODEL
OPENAI_WHISPER = OPENAI_TRANSCRIPTION_MODEL
OPENAI_GPT_5_4_AGENT = OPENAI_BEST_AGENT
OPENAI_GPT_5_2_AGENT = OPENAI_MEDIUM_AGENT
OPENAI_GPT_4O_AGENT = OPENAI_STANDARD_AGENT
OPENAI_GPT_4O_MINI_AGENT = OPENAI_FAST_AGENT
OPENAI_O1_AGENT = OPENAI_REASONING_AGENT

CLAUDE_OPUS_4_7 = ANTHROPIC_BEST_MODEL
CLAUDE_SONNET_4_6 = ANTHROPIC_MEDIUM_MODEL
CLAUDE_SONNET_4_5 = ANTHROPIC_FALLBACK_MODEL
CLAUDE_HAIKU_4_5 = ANTHROPIC_FAST_MODEL
CLAUDE_OPUS_5 = ANTHROPIC_OPUS_5_MODEL
CLAUDE_SONNET_5 = ANTHROPIC_SONNET_5_MODEL
CLAUDE_3_5_SONNET_ALIAS = ANTHROPIC_COMPATIBILITY_ALIAS
CLAUDE_3_5_SONNET_VERSIONED = ANTHROPIC_COMPATIBILITY_MODEL
CLAUDE_OPUS_4_7_AGENT = ANTHROPIC_BEST_AGENT
CLAUDE_SONNET_4_6_AGENT = ANTHROPIC_MEDIUM_AGENT
CLAUDE_SONNET_4_5_AGENT = ANTHROPIC_FALLBACK_AGENT
CLAUDE_HAIKU_4_5_AGENT = ANTHROPIC_FAST_AGENT
CLAUDE_OPUS_5_AGENT = ANTHROPIC_OPUS_5_AGENT
CLAUDE_SONNET_5_AGENT = ANTHROPIC_SONNET_5_AGENT

FABLE_5_1 = FABLE_BEST_MODEL
FABLE_5_1_AGENT = FABLE_BEST_AGENT

DEEPSEEK_V4_PRO = DEEPSEEK_BEST_MODEL
DEEPSEEK_V4_FLASH = DEEPSEEK_FAST_MODEL
DEEPSEEK_REASONER = DEEPSEEK_REASONING_MODEL
DEEPSEEK_CHAT_ALIAS = DEEPSEEK_CHAT_MODEL
DEEPSEEK_V4_PRO_AGENT = DEEPSEEK_BEST_AGENT
DEEPSEEK_V4_FLASH_AGENT = DEEPSEEK_FAST_AGENT
DEEPSEEK_REASONER_AGENT = DEEPSEEK_REASONING_AGENT
DEEPSEEK_CHAT_ALIAS_AGENT = DEEPSEEK_CHAT_AGENT

GEMINI_2_FLASH_LITE = GOOGLE_FAST_MODEL
GEMINI_2_5_FLASH_IMAGE = GOOGLE_IMAGE_MODEL
GEMINI_3_PRO_IMAGE_PREVIEW = GOOGLE_BEST_IMAGE_MODEL
IMAGEN_4 = GOOGLE_IMAGE_GENERATION_MODEL
GEMINI_2_FLASH_LITE_AGENT = GOOGLE_FAST_AGENT


ALL_MODEL_IDS = frozenset(
    value
    for name, value in globals().copy().items()
    if name.isupper() and isinstance(value, str)
)